ex:1803.CountPairsWithXORinaRange 2416.SumofPrefixScoresofStrings
1803.CountPairsWithXORinaRange:1803.CountPairsWithXORinaRange.cc
	g++ -Wall -g $^ -o $@
2416.SumofPrefixScoresofStrings:2416.SumofPrefixScoresofStrings.cc lib.a
	g++ -Wall -g $^ -o $@
clean:
	rm -f 1803.CountPairsWithXORinaRange 2416.SumofPrefixScoresofStrings
