ex:51.N-Queens 52.N-QueensII
51.N-Queens:51.N-Queens.h 51.N-Queens.cc lib.a
	g++ -g -Wall $^ -o $@ 
52.N-QueensII:52.N-QueensII.h 52.N-QueensII.cc lib.a
	g++ -g -Wall $^ -o $@ 
clean:
	rm -f 51.N-Queens 52.N-QueensII *.o lib.a

