ex:1535.FindtheWinnerofanArrayGame 1536.MinimumSwapstoArrangeaBinaryGrid 1551.MinimumOperationstoMakeArrayEqual 1557.MinimumNumberofVerticestoReachAllNodes 1578.MinimumTimetoMakeRopeColorful 1642.FurthestBuildingYouCanReach 1686.StoneGameVI 2211.CountCollisionsonaRoad 2126.DestroyingAsteroids 2170.MinimumOperationstoMaketheArrayAlternating 2207.MaximizeNumberofSubsequencesinaString 2216.MinimumDeletionstoMakeArrayBeautiful 2242.MaximumScoreofaNodeSequence 2259.RemoveDigitFromNumbertoMaximizeResult
1535.FindtheWinnerofanArrayGame:1535.FindtheWinnerofanArrayGame.cc
	g++ -Wall -g $^ -o $@
1536.MinimumSwapstoArrangeaBinaryGrid:1536.MinimumSwapstoArrangeaBinaryGrid.cc
	g++ -Wall -g $^ -o $@
1551.MinimumOperationstoMakeArrayEqual:1551.MinimumOperationstoMakeArrayEqual.cc
	g++ -Wall -g $^ -o $@
1557.MinimumNumberofVerticestoReachAllNodes:1557.MinimumNumberofVerticestoReachAllNodes.cc lib.a
	g++ -Wall -g $^ -o $@
1578.MinimumTimetoMakeRopeColorful:1578.MinimumTimetoMakeRopeColorful.cc
	g++ -Wall -g $^ -o $@
1642.FurthestBuildingYouCanReach:1642.FurthestBuildingYouCanReach.cc
	g++ -Wall -g $^ -o $@
1686.StoneGameVI:1686.StoneGameVI.cc
	g++ -Wall -g $^ -o $@
2211.CountCollisionsonaRoad:2211.CountCollisionsonaRoad.cc
	g++ -Wall -g $^ -o $@
2126.DestroyingAsteroids:2126.DestroyingAsteroids.cc
	g++ -Wall -g $^ -o $@
2170.MinimumOperationstoMaketheArrayAlternating:2170.MinimumOperationstoMaketheArrayAlternating.cc
	g++ -Wall -g $^ -o $@
2207.MaximizeNumberofSubsequencesinaString:2207.MaximizeNumberofSubsequencesinaString.cc
	g++ -Wall -g $^ -o $@
2216.MinimumDeletionstoMakeArrayBeautiful:2216.MinimumDeletionstoMakeArrayBeautiful.cc
	g++ -Wall -g $^ -o $@
2242.MaximumScoreofaNodeSequence:2242.MaximumScoreofaNodeSequence.cc
	g++ -Wall -g $^ -o $@
2259.RemoveDigitFromNumbertoMaximizeResult:2259.RemoveDigitFromNumbertoMaximizeResult.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 1535.FindtheWinnerofanArrayGame 1536.MinimumSwapstoArrangeaBinaryGrid 1551.MinimumOperationstoMakeArrayEqual 1557.MinimumNumberofVerticestoReachAllNodes 1642.FurthestBuildingYouCanReach 1686.StoneGameVI 2211.CountCollisionsonaRoad 2126.DestroyingAsteroids 2170.MinimumOperationstoMaketheArrayAlternating 2207.MaximizeNumberofSubsequencesinaString 2216.MinimumDeletionstoMakeArrayBeautiful 2242.MaximumScoreofaNodeSequence 2259.RemoveDigitFromNumbertoMaximizeResult
