ex:lib.a 309.BestTimetoBuyandSellStockwithCooldown 375.GuessNumberHigherorLowerII 464.CanIWin 576.OutofBoundaryPaths 600.Non-negativeIntegerswithoutConsecutiveOnes 698.PartitiontoKEqualSumSubsets 764.LargestPlusSign 787.CheapestFlightsWithinKStops 790.DominoandTrominoTiling 837.New21Game 1027.LongestArithmeticSubsequence 1320.MinimumDistancetoTypeaWordUsingTwoFingers 1477.FindTwoNon-overlappingSub-arraysEachWithTargetSum 1510.StoneGameIV 1547.MinimumCosttoCutaStick 1563.StoneGameV 1567.MaximumLengthofSubarrayWithPositiveProduct 1594.MaximumNonNegativeProductinaMatrix 1621.NumberofSetsofKNon-OverlappingLineSegments 1626.BestTeamWithNoConflicts 1955.CountNumberofSpecialSubsequences 2054.TwoBestNon-OverlappingEvents 2218.MaximumValueofKCoinsFromPiles 2222.NumberofWaystoSelectBuildings 2240.NumberofWaystoBuyPensandPencils 2266.CountNumberofTexts  2304.MinimumPathCostinaGrid 2320.CountNumberofWaystoPlaceHouses  2327.NumberofPeopleAwareofaSecret
lib.a:head.o
	ar -crv $@ $<
head.o:head.cc
309.BestTimetoBuyandSellStockwithCooldown:309.BestTimetoBuyandSellStockwithCooldown.cc
	g++ -Wall -g $^ -o $@
375.GuessNumberHigherorLowerII:375.GuessNumberHigherorLowerII.cc
	g++ -Wall -g $^ -o $@
464.CanIWin:464.CanIWin.cc
	g++ -Wall -g $^ -o $@
576.OutofBoundaryPaths:576.OutofBoundaryPaths.cc
	g++ -Wall -g $^ -o $@
600.Non-negativeIntegerswithoutConsecutiveOnes:600.Non-negativeIntegerswithoutConsecutiveOnes.cc
	g++ -Wall -g $^ -o $@
698.PartitiontoKEqualSumSubsets:698.PartitiontoKEqualSumSubsets.cc
	g++ -Wall -g $^ -o $@
764.LargestPlusSign:764.LargestPlusSign.cc
	g++ -Wall -g $^ -o $@
787.CheapestFlightsWithinKStops:787.CheapestFlightsWithinKStops.cc
	g++ -Wall -g $^ -o $@
790.DominoandTrominoTiling:790.DominoandTrominoTiling.cc
	g++ -Wall -g $^ -o $@
837.New21Game:837.New21Game.cc
	g++ -Wall -g $^ -o $@
1027.LongestArithmeticSubsequence:1027.LongestArithmeticSubsequence.cc
	g++ -Wall -g -std=c++11  $^ -o $@
1320.MinimumDistancetoTypeaWordUsingTwoFingers:1320.MinimumDistancetoTypeaWordUsingTwoFingers.cc
	g++ -Wall -g $^ -o $@
1477.FindTwoNon-overlappingSub-arraysEachWithTargetSum:1477.FindTwoNon-overlappingSub-arraysEachWithTargetSum.cc
	g++ -Wall -g $^ -o $@
1510.StoneGameIV:1510.StoneGameIV.cc
	g++ -Wall -g $^ -o $@
1547.MinimumCosttoCutaStick:1547.MinimumCosttoCutaStick.cc
	g++ -Wall -g $^ -o $@
1563.StoneGameV:1563.StoneGameV.cc
	g++ -Wall -g $^ -o $@
1567.MaximumLengthofSubarrayWithPositiveProduct:1567.MaximumLengthofSubarrayWithPositiveProduct.cc
	g++ -Wall -g $^ -o $@
1594.MaximumNonNegativeProductinaMatrix:1594.MaximumNonNegativeProductinaMatrix.cc
	g++ -Wall -g $^ -o $@
1621.NumberofSetsofKNon-OverlappingLineSegments:1621.NumberofSetsofKNon-OverlappingLineSegments.cc
	g++ -Wall -g $^ -o $@
1626.BestTeamWithNoConflicts:1626.BestTeamWithNoConflicts.cc
	g++ -Wall -g $^ -o $@
1955.CountNumberofSpecialSubsequences:1955.CountNumberofSpecialSubsequences.cc
	g++ -Wall -g $^ -o $@
2054.TwoBestNon-OverlappingEvents:2054.TwoBestNon-OverlappingEvents.cc
	g++ -Wall -g $^ -o $@
2218.MaximumValueofKCoinsFromPiles:2218.MaximumValueofKCoinsFromPiles.cc
	g++ -Wall -g $^ -o $@
2222.NumberofWaystoSelectBuildings:2222.NumberofWaystoSelectBuildings.cc
	g++ -Wall -g $^ -o $@
2240.NumberofWaystoBuyPensandPencils:2240.NumberofWaystoBuyPensandPencils.cc
	g++ -Wall -g $^ -o $@
2266.CountNumberofTexts:2266.CountNumberofTexts.cc
	g++ -Wall -g $^ -o $@
2304.MinimumPathCostinaGrid:2304.MinimumPathCostinaGrid.cc
	g++ -Wall -g $^ -o $@
2320.CountNumberofWaystoPlaceHouses:2320.CountNumberofWaystoPlaceHouses.cc
	g++ -Wall -g $^ -o $@
2327.NumberofPeopleAwareofaSecret:2327.NumberofPeopleAwareofaSecret.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 309.BestTimetoBuyandSellStockwithCooldown 375.GuessNumberHigherorLowerII 464.CanIWin 576.OutofBoundaryPaths 600.Non-negativeIntegerswithoutConsecutiveOnes 698.PartitiontoKEqualSumSubsets 764.LargestPlusSign 787.CheapestFlightsWithinKStops 790.DominoandTrominoTiling 837.New21Game 1027.LongestArithmeticSubsequence 1320.MinimumDistancetoTypeaWordUsingTwoFingers 1477.FindTwoNon-overlappingSub-arraysEachWithTargetSum 1510.StoneGameIV 1547.MinimumCosttoCutaStick 1563.StoneGameV 1567.MaximumLengthofSubarrayWithPositiveProduct 1594.MaximumNonNegativeProductinaMatrix 1621.NumberofSetsofKNon-OverlappingLineSegments  1955.CountNumberofSpecialSubsequences 2054.TwoBestNon-OverlappingEvents 2218.MaximumValueofKCoinsFromPiles 2222.NumberofWaystoSelectBuildings 2240.NumberofWaystoBuyPensandPencils 2266.CountNumberofTexts 2304.MinimumPathCostinaGrid 2320.CountNumberofWaystoPlaceHouses 2327.NumberofPeopleAwareofaSecret
