ex:1080.InsufficientNodesinRoottoLeafPaths 1376.TimeNeededtoInformAllEmployees 1034.ColoringABorder
lib.a:head.o
	ar -crv $@ $<
head.o:head.cc
1080.InsufficientNodesinRoottoLeafPaths:1080.InsufficientNodesinRoottoLeafPaths.cc lib.a
	g++ -Wall -g $^ -o $@
1376.TimeNeededtoInformAllEmployees:1376.TimeNeededtoInformAllEmployees.cc
	g++ -Wall -g $^ -o $@
1034.ColoringABorder:1034.ColoringABorder.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 1080.InsufficientNodesinRoottoLeafPaths 1376.TimeNeededtoInformAllEmployees 1034.ColoringABorder
