ex:lib.a  1713.MinimumOperationstoMakeaSubsequence 2179.CountGoodTripletsinanArray
lib.a:head.o
	ar -crv $@ $<
head.o:head.cc
1713.MinimumOperationstoMakeaSubsequence:1713.MinimumOperationstoMakeaSubsequence.cc
	g++ -Wall -g $^ -o $@
2179.CountGoodTripletsinanArray:2179.CountGoodTripletsinanArray.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 1713.MinimumOperationstoMakeaSubsequence


