ex:2398.MaximumNumberofRobotsWithinBudget 2537.CounttheNumberofGoodSubarrays 2555.MaximizeWinFromTwoSegments 2563.CounttheNumberofFairPairs
2398.MaximumNumberofRobotsWithinBudget:2398.MaximumNumberofRobotsWithinBudget.cc
	g++ -Wall -g $^ -o $@
2537.CounttheNumberofGoodSubarrays:2537.CounttheNumberofGoodSubarrays.cc
	g++ -Wall -g $^ -o $@
2555.MaximizeWinFromTwoSegments:2555.MaximizeWinFromTwoSegments.cc
	g++ -Wall -g $^ -o $@
2563.CounttheNumberofFairPairs:2563.CounttheNumberofFairPairs.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 2398.MaximumNumberofRobotsWithinBudget 2537.CounttheNumberofGoodSubarrays 2555.MaximizeWinFromTwoSegments 2563.CounttheNumberofFairPairs
