ex:336.PalindromePairs 1224.MaximumEqualFrequency 1452.PeopleWhoseListofFavoriteCompaniesIsNotaSubsetofAnotherList 1540.CanConvertStringinKMoves 1657.DetermineifTwoStringsAreClose 1733.MinimumNumberofPeopletoTeach 2223.SumofScoresofBuiltStrings 2456.MostPopularVideoCreator 2531.MakeNumberofDistinctCharactersEqual 2540.MinimumCommonValue
lib.a:head.o
	ar -crv $@ $<
head.o:head.cc
336.PalindromePairs:336.PalindromePairs.cc lib.a
	g++ -Wall -g -std=c++11 $^ -o $@
1224.MaximumEqualFrequency:1224.MaximumEqualFrequency.cc
	g++ -Wall -g $^ -o $@
1452.PeopleWhoseListofFavoriteCompaniesIsNotaSubsetofAnotherList:1452.PeopleWhoseListofFavoriteCompaniesIsNotaSubsetofAnotherList.cc lib.a
	g++ -Wall -g $^ -o $@
1540.CanConvertStringinKMoves:1540.CanConvertStringinKMoves.cc
	g++ -Wall -g $^ -o $@
1657.DetermineifTwoStringsAreClose:1657.DetermineifTwoStringsAreClose.cc
	g++ -Wall -g $^ -o $@
1733.MinimumNumberofPeopletoTeach:1733.MinimumNumberofPeopletoTeach.cc
	g++ -Wall -g $^ -o $@
2223.SumofScoresofBuiltStrings:2223.SumofScoresofBuiltStrings.cc
	g++ -Wall -g $^ -o $@
2430.MaximumDeletionsonaString:2430.MaximumDeletionsonaString.cc
	g++ -Wall -g $^ -o $@
2456.MostPopularVideoCreator:2456.MostPopularVideoCreator.cc lib.a
	g++ -Wall -g $^ -o $@
2531.MakeNumberofDistinctCharactersEqual:2531.MakeNumberofDistinctCharactersEqual.cc
	g++ -Wall -g $^ -o $@
2540.MinimumCommonValue:2540.MinimumCommonValue.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 336.PalindromePairs 1224.MaximumEqualFrequency 1452.PeopleWhoseListofFavoriteCompaniesIsNotaSubsetofAnotherList 1540.CanConvertStringinKMoves 1657.DetermineifTwoStringsAreClose 1733.MinimumNumberofPeopletoTeach 2223.SumofScoresofBuiltStrings 2430.MaximumDeletionsonaString 2456.MostPopularVideoCreator 2531.MakeNumberofDistinctCharactersEqual 2540.MinimumCommonValue
