ex:336.PalindromePairs 1452.PeopleWhoseListofFavoriteCompaniesIsNotaSubsetofAnotherList 2223.SumofScoresofBuiltStrings 2430.MaximumDeletionsonaString 2531.MakeNumberofDistinctCharactersEqual 2540.MinimumCommonValue
336.PalindromePairs:336.PalindromePairs.cc lib.a
	g++ -Wall -g -std=c++11 $^ -o $@
1452.PeopleWhoseListofFavoriteCompaniesIsNotaSubsetofAnotherList:1452.PeopleWhoseListofFavoriteCompaniesIsNotaSubsetofAnotherList.cc lib.a
	g++ -Wall -g $^ -o $@
2223.SumofScoresofBuiltStrings:2223.SumofScoresofBuiltStrings.cc
	g++ -Wall -g $^ -o $@
2430.MaximumDeletionsonaString:2430.MaximumDeletionsonaString.cc
	g++ -Wall -g $^ -o $@
2531.MakeNumberofDistinctCharactersEqual:2531.MakeNumberofDistinctCharactersEqual.cc
	g++ -Wall -g $^ -o $@
2540.MinimumCommonValue:2540.MinimumCommonValue.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 336.PalindromePairs 1452.PeopleWhoseListofFavoriteCompaniesIsNotaSubsetofAnotherList 2223.SumofScoresofBuiltStrings 2430.MaximumDeletionsonaString 2531.MakeNumberofDistinctCharactersEqual 2540.MinimumCommonValue
