ex:135.Candy 753.CrackingtheSafe 2065.MaximumPathQualityofaGraph
135.Candy:135.Candy.cc
	g++ -Wall -g $^ -o $@
753.CrackingtheSafe:753.CrackingtheSafe.cc
	g++ -Wall -g $^ -o $@
2065.MaximumPathQualityofaGraph:2065.MaximumPathQualityofaGraph.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 135.Candy 753.CrackingtheSafe 2065.MaximumPathQualityofaGraph

