ex:133.CloneGraph 135.Candy 399.EvaluateDivision 753.CrackingtheSafe 834.SumofDistancesinTree 934.ShortestBridge 1129.ShortestPathwithAlternatingColors 1334.FindtheCityWiththeSmallestNumberofNeighborsataThresholdDistance 1514.PathwithMaximumProbability 1519.NumberofNodesintheSub-TreeWiththeSameLabel 1615.MaximalNetworkRank 1786.NumberofRestrictedPathsFromFirsttoLastNode 1976.NumberofWaystoArriveatDestination 2045.SecondMinimumTimetoReachDestination 2065.MaximumPathQualityofaGraph 2581.CountNumberofPossibleRootNodes 2608.ShortestCycleinaGraph 2642.DesignGraphWithShortestPathCalculator 2646.MinimizetheTotalPriceoftheTrips
lib.a:head.o
	ar -crv $@ $<
head.o:head.cc
133.CloneGraph:133.CloneGraph.cc
	g++ -Wall -g $^ -o $@
135.Candy:135.Candy.cc
	g++ -Wall -g $^ -o $@
399.EvaluateDivision:399.EvaluateDivision.cc lib.a
	g++ -Wall -g $^ -o $@
753.CrackingtheSafe:753.CrackingtheSafe.cc
	g++ -Wall -g $^ -o $@
834.SumofDistancesinTree:834.SumofDistancesinTree.cc lib.a
	g++ -Wall -g $^ -o $@
934.ShortestBridge:934.ShortestBridge.cc
	g++ -Wall -g $^ -o $@
1129.ShortestPathwithAlternatingColors:1129.ShortestPathwithAlternatingColors.cc lib.a
	g++ -Wall -g $^ -o $@
1334.FindtheCityWiththeSmallestNumberofNeighborsataThresholdDistance:1334.FindtheCityWiththeSmallestNumberofNeighborsataThresholdDistance.cc
	g++ -Wall -g $^ -o $@
1514.PathwithMaximumProbability:1514.PathwithMaximumProbability.cc
	g++ -Wall -g $^ -o $@
1519.NumberofNodesintheSub-TreeWiththeSameLabel:1519.NumberofNodesintheSub-TreeWiththeSameLabel.cc lib.a
	g++ -Wall -g $^ -o $@
1615.MaximalNetworkRank:1615.MaximalNetworkRank.cc
	g++ -Wall -g $^ -o $@
1786.NumberofRestrictedPathsFromFirsttoLastNode:1786.NumberofRestrictedPathsFromFirsttoLastNode.cc
	g++ -Wall -g $^ -o $@
1976.NumberofWaystoArriveatDestination:1976.NumberofWaystoArriveatDestination.cc
	g++ -Wall -g $^ -o $@
2045.SecondMinimumTimetoReachDestination:2045.SecondMinimumTimetoReachDestination.cc
	g++ -Wall -g $^ -o $@
2065.MaximumPathQualityofaGraph:2065.MaximumPathQualityofaGraph.cc
	g++ -Wall -g $^ -o $@
2581.CountNumberofPossibleRootNodes:2581.CountNumberofPossibleRootNodes.cc
	g++ -Wall -g $^ -o $@
2608.ShortestCycleinaGraph:2608.ShortestCycleinaGraph.cc
	g++ -Wall -g $^ -o $@
2642.DesignGraphWithShortestPathCalculator:2642.DesignGraphWithShortestPathCalculator.cc lib.a
	g++ -Wall -g $^ -o $@
2646.MinimizetheTotalPriceoftheTrips:2646.MinimizetheTotalPriceoftheTrips.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 133.CloneGraph 135.Candy 399.EvaluateDivision 753.CrackingtheSafe 834.SumofDistancesinTree 934.ShortestBridge 1129.ShortestPathwithAlternatingColors 1334.FindtheCityWiththeSmallestNumberofNeighborsataThresholdDistance 1514.PathwithMaximumProbability 1519.NumberofNodesintheSub-TreeWiththeSameLabel 1615.MaximalNetworkRank 1786.NumberofRestrictedPathsFromFirsttoLastNode 2045.SecondMinimumTimetoReachDestination 1976.NumberofWaystoArriveatDestination 2065.MaximumPathQualityofaGraph 2581.CountNumberofPossibleRootNodes 2608.ShortestCycleinaGraph 2642.DesignGraphWithShortestPathCalculator 2646.MinimizetheTotalPriceoftheTrips
