ex:135.Candy 753.CrackingtheSafe 834.SumofDistancesinTree 1129.ShortestPathwithAlternatingColors 1334.FindtheCityWiththeSmallestNumberofNeighborsataThresholdDistance 1615.MaximalNetworkRank 2045.SecondMinimumTimetoReachDestination 2065.MaximumPathQualityofaGraph 2608.ShortestCycleinaGraph
lib.a:head.o
	ar -crv $@ $<
head.o:head.cc
135.Candy:135.Candy.cc
	g++ -Wall -g $^ -o $@
753.CrackingtheSafe:753.CrackingtheSafe.cc
	g++ -Wall -g $^ -o $@
834.SumofDistancesinTree:834.SumofDistancesinTree.cc lib.a
	g++ -Wall -g $^ -o $@
1129.ShortestPathwithAlternatingColors:1129.ShortestPathwithAlternatingColors.cc lib.a
	g++ -Wall -g $^ -o $@
1334.FindtheCityWiththeSmallestNumberofNeighborsataThresholdDistance:1334.FindtheCityWiththeSmallestNumberofNeighborsataThresholdDistance.cc
	g++ -Wall -g $^ -o $@
1615.MaximalNetworkRank:1615.MaximalNetworkRank.cc
	g++ -Wall -g $^ -o $@
2045.SecondMinimumTimetoReachDestination:2045.SecondMinimumTimetoReachDestination.cc
	g++ -Wall -g $^ -o $@
2065.MaximumPathQualityofaGraph:2065.MaximumPathQualityofaGraph.cc
	g++ -Wall -g $^ -o $@
2608.ShortestCycleinaGraph:2608.ShortestCycleinaGraph.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 135.Candy 753.CrackingtheSafe 834.SumofDistancesinTree 1129.ShortestPathwithAlternatingColors 1334.FindtheCityWiththeSmallestNumberofNeighborsataThresholdDistance 1615.MaximalNetworkRank 2045.SecondMinimumTimetoReachDestination 2065.MaximumPathQualityofaGraph 2608.ShortestCycleinaGraph
