ex:478.GenerateRandomPointinaCircle 592.FractionAdditionandSubtraction 883.ProjectionAreaof3DShapes 892.SurfaceAreaof3DShapes 2125.NumberofLaserBeamsinaBank 1227.AirplaneSeatAssignmentProbability 1344.AngleBetweenHandsofaClock 1354.ConstructTargetArrayWithMultipleSums 1551.MinimumOperationstoMakeArrayEqual 1862.SumofFlooredPairs 1884.EggDropWith2EggsandNFloors 1969.MinimumNon-ZeroProductoftheArrayElements 2222.NumberofWaystoSelectBuildings 2224.MinimumNumberofOperationstoConvertTime 2310.SumofNumbersWithUnitsDigitK 2352.EqualRowandColumnPairs 2550.CountCollisionsofMonkeysonaPolygon 2575.FindtheDivisibilityArrayofaString
lib.a:head.o
	ar -crv $@ $<
head.o:head.cc
372.SuperPow:372.SuperPow.cc
	g++ -Wall -g $^ -o $@
470:470.cc
	g++ -Wall -g $^ -o $@
478.GenerateRandomPointinaCircle:478.GenerateRandomPointinaCircle.cc lib.a
	g++ -Wall -g $^ -o $@
592.FractionAdditionandSubtraction:592.FractionAdditionandSubtraction.cc
	g++ -Wall -g $^ -o $@
883.ProjectionAreaof3DShapes:883.ProjectionAreaof3DShapes.cc
	g++ -Wall -g $^ -o $@
892.SurfaceAreaof3DShapes:892.SurfaceAreaof3DShapes.cc
	g++ -Wall -g $^ -o $@
1175.PrimeArrangements:1175.PrimeArrangements.cc
	g++ -Wall -g $^ -o $@
1227.AirplaneSeatAssignmentProbability:1227.AirplaneSeatAssignmentProbability.cc
	g++ -Wall -g $^ -o $@
1344.AngleBetweenHandsofaClock:1344.AngleBetweenHandsofaClock.cc
	g++ -Wall -g $^ -o $@
1354.ConstructTargetArrayWithMultipleSums:1354.ConstructTargetArrayWithMultipleSums.cc
	g++ -Wall -g $^ -o $@
1551.MinimumOperationstoMakeArrayEqual:1551.MinimumOperationstoMakeArrayEqual.cc
	g++ -Wall -g $^ -o $@
1621.NumberofSetsofKNon-OverlappingLineSegments:1621.NumberofSetsofKNon-OverlappingLineSegments.cc
	g++ -Wall -g $^ -o $@
1688.CountofMatchesinTournament:1688.CountofMatchesinTournament.cc
	g++ -Wall -g $^ -o $@
1862.SumofFlooredPairs:1862.SumofFlooredPairs.cc
	g++ -Wall -g $^ -o $@
1884.EggDropWith2EggsandNFloors:1884.EggDropWith2EggsandNFloors.cc
	g++ -Wall -g $^ -o $@
1969.MinimumNon-ZeroProductoftheArrayElements:1969.MinimumNon-ZeroProductoftheArrayElements.cc
	g++ -Wall -g $^ -o $@
2125.NumberofLaserBeamsinaBank:2125.NumberofLaserBeamsinaBank.cc
	g++ -Wall -g $^ -o $@
2217.FindPalindromeWithFixedLength:2217.FindPalindromeWithFixedLength.cc
	g++ -Wall -g $^ -o $@
2222.NumberofWaystoSelectBuildings:2222.NumberofWaystoSelectBuildings.cc
	g++ -Wall -g $^ -o $@
2224.MinimumNumberofOperationstoConvertTime:2224.MinimumNumberofOperationstoConvertTime.cc
	g++ -Wall -g $^ -o $@
2310.SumofNumbersWithUnitsDigitK:2310.SumofNumbersWithUnitsDigitK.cc
	g++ -Wall -g $^ -o $@
2344.MinimumDeletionstoMakeArrayDivisible:2344.MinimumDeletionstoMakeArrayDivisible.cc
	g++ -Wall -g $^ -o $@
2352.EqualRowandColumnPairs:2352.EqualRowandColumnPairs.cc
	g++ -Wall -g $^ -o $@
2550.CountCollisionsofMonkeysonaPolygon:2550.CountCollisionsofMonkeysonaPolygon.cc
	g++ -Wall -g $^ -o $@
2575.FindtheDivisibilityArrayofaString:2575.FindtheDivisibilityArrayofaString.cc lib.a
	g++ -Wall -g $^ -o $@
clean:
	rm -f 372.SuperPow 470 478.GenerateRandomPointinaCircle 592.FractionAdditionandSubtraction 1175.PrimeArrangements 1227.AirplaneSeatAssignmentProbability 1344.AngleBetweenHandsofaClock 1354.ConstructTargetArrayWithMultipleSums 1551.MinimumOperationstoMakeArrayEqual 1621.NumberofSetsofKNon-OverlappingLineSegments 1688.CountofMatchesinTournament 1862.SumofFlooredPairs 1884.EggDropWith2EggsandNFloors 1969.MinimumNon-ZeroProductoftheArrayElements 2125.NumberofLaserBeamsinaBank 2217.FindPalindromeWithFixedLength 2222.NumberofWaystoSelectBuildings 2224.MinimumNumberofOperationstoConvertTime 2310.SumofNumbersWithUnitsDigitK 2344.MinimumDeletionstoMakeArrayDivisible 2352.EqualRowandColumnPairs 2550.CountCollisionsofMonkeysonaPolygon 2575.FindtheDivisibilityArrayofaString
