ex:773.SlidingPuzzle 818.RaceCar 1293.ShortestPathinaGridwithObstaclesElimination 1654.MinimumJumpstoReachHome 2146.KHighestRankedItemsWithinaPriceRange
lib.a:head.o
	ar -crv $@ $<
head.o:head.cc
773.SlidingPuzzle:773.SlidingPuzzle.cc
	g++ -Wall -g $^ -o $@
818.RaceCar:818.RaceCar.cc
	g++ -Wall -g $^ -o $@
1293.ShortestPathinaGridwithObstaclesElimination:1293.ShortestPathinaGridwithObstaclesElimination.cc
	g++ -Wall -g $^ -o $@
1654.MinimumJumpstoReachHome:1654.MinimumJumpstoReachHome.cc
	g++ -Wall -g $^ -o $@
2146.KHighestRankedItemsWithinaPriceRange:2146.KHighestRankedItemsWithinaPriceRange.cc lib.a
	g++ -Wall -g $^ -o $@
clean:
	rm -f 773.SlidingPuzzle 818.RaceCar 1293.ShortestPathinaGridwithObstaclesElimination 1654.MinimumJumpstoReachHome 2146.KHighestRankedItemsWithinaPriceRange
