ex:773.SlidingPuzzle 818.RaceCar 1293.ShortestPathinaGridwithObstaclesElimination
773.SlidingPuzzle:773.SlidingPuzzle.cc
	g++ -Wall -g $^ -o $@
818.RaceCar:818.RaceCar.cc
	g++ -Wall -g $^ -o $@
1293.ShortestPathinaGridwithObstaclesElimination:1293.ShortestPathinaGridwithObstaclesElimination.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 773.SlidingPuzzle 818.RaceCar 1293.ShortestPathinaGridwithObstaclesElimination
