ex:1383.MaximumPerformanceofaTeam 1675.MinimizeDeviationinArray 1882.ProcessTasksUsingServers 1943.DescribethePainting 2208.MinimumOperationstoHalveArraySum 2402.MeetingRoomsIII 2530.MaximalScoreAfterApplyingKOperations 2542.MaximumSubsequenceScore 2558.TakeGiftsFromtheRichestPile 2583.KthLargestSuminaBinaryTree 2593.FindScoreofanArrayAfterMarkingAllElements 
lib.a:head.o
	ar -crv $@ $<
head.o:head.cc
1354.ConstructTargetArrayWithMultipleSums:1354.ConstructTargetArrayWithMultipleSums.cc
	g++ -Wall -g $^ -o $@
1383.MaximumPerformanceofaTeam:1383.MaximumPerformanceofaTeam.cc
	g++ -Wall -g $^ -o $@
1675.MinimizeDeviationinArray:1675.MinimizeDeviationinArray.cc
	g++ -Wall -g $^ -o $@
1882.ProcessTasksUsingServers:1882.ProcessTasksUsingServers.cc lib.a
	g++ -Wall -g $^ -o $@
1943.DescribethePainting:1943.DescribethePainting.cc lib.a
	g++ -Wall -g $^ -o $@
2208.MinimumOperationstoHalveArraySum:2208.MinimumOperationstoHalveArraySum.cc
	g++ -Wall -g $^ -o $@
2402.MeetingRoomsIII:2402.MeetingRoomsIII.cc
	g++ -Wall -g $^ -o $@
2530.MaximalScoreAfterApplyingKOperations:2530.MaximalScoreAfterApplyingKOperations.cc
	g++ -Wall -g $^ -o $@
2542.MaximumSubsequenceScore:2542.MaximumSubsequenceScore.cc
	g++ -Wall -g $^ -o $@
2558.TakeGiftsFromtheRichestPile:2558.TakeGiftsFromtheRichestPile.cc
	g++ -Wall -g $^ -o $@
2583.KthLargestSuminaBinaryTree:2583.KthLargestSuminaBinaryTree.cc lib.a
	g++ -Wall -g $^ -o $@
2593.FindScoreofanArrayAfterMarkingAllElements:2593.FindScoreofanArrayAfterMarkingAllElements.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 1354.ConstructTargetArrayWithMultipleSums 1383.MaximumPerformanceofaTeam 1675.MinimizeDeviationinArray 1882.ProcessTasksUsingServers 1943.DescribethePainting 2208.MinimumOperationstoHalveArraySum 2402.MeetingRoomsIII 2530.MaximalScoreAfterApplyingKOperations 2542.MaximumSubsequenceScore 2558.TakeGiftsFromtheRichestPile 2583.KthLargestSuminaBinaryTree 2593.FindScoreofanArrayAfterMarkingAllElements 
