ex:1354.ConstructTargetArrayWithMultipleSums 2208.MinimumOperationstoHalveArraySum 2402.MeetingRoomsIII 2530.MaximalScoreAfterApplyingKOperations 2542.MaximumSubsequenceScore 2558.TakeGiftsFromtheRichestPile
1354.ConstructTargetArrayWithMultipleSums:1354.ConstructTargetArrayWithMultipleSums.cc
	g++ -Wall -g $^ -o $@
2208.MinimumOperationstoHalveArraySum:2208.MinimumOperationstoHalveArraySum.cc
	g++ -Wall -g $^ -o $@
2402.MeetingRoomsIII:2402.MeetingRoomsIII.cc
	g++ -Wall -g $^ -o $@
2530.MaximalScoreAfterApplyingKOperations:2530.MaximalScoreAfterApplyingKOperations.cc
	g++ -Wall -g $^ -o $@
2542.MaximumSubsequenceScore:2542.MaximumSubsequenceScore.cc
	g++ -Wall -g $^ -o $@
2558.TakeGiftsFromtheRichestPile:2558.TakeGiftsFromtheRichestPile.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 1354.ConstructTargetArrayWithMultipleSums 2208.MinimumOperationstoHalveArraySum 2402.MeetingRoomsIII 2530.MaximalScoreAfterApplyingKOperations 2542.MaximumSubsequenceScore 2558.TakeGiftsFromtheRichestPile
