ex:839.SimilarStringGroups 2157.GroupsofStrings
839.SimilarStringGroups:839.SimilarStringGroups.cc
	g++ -Wall -g $^ -o  $@
2157.GroupsofStrings:2157.GroupsofStrings.cc lib.a
	g++ -Wall -g $^ -o  $@
clean:
	rm -f 839.SimilarStringGroups 2157.GroupsofStrings
