ex:214.ShortestPalindrome 1392.LongestHappyPrefix 1910.RemoveAllOccurrencesofaSubstring 2430.MaximumDeletionsonaString 2565.SubsequenceWiththeMinimumScore
214.ShortestPalindrome:214.ShortestPalindrome.cc
	g++ -Wall -g $^ -o  $@
1392.LongestHappyPrefix:1392.LongestHappyPrefix.cc
	g++ -Wall -g $^ -o  $@
1910.RemoveAllOccurrencesofaSubstring:1910.RemoveAllOccurrencesofaSubstring.cc
	g++ -Wall -g $^ -o  $@
2430.MaximumDeletionsonaString:2430.MaximumDeletionsonaString.cc
	g++ -Wall -g $^ -o  $@
2565.SubsequenceWiththeMinimumScore:2565.SubsequenceWiththeMinimumScore.cc
	g++ -Wall -g $^ -o  $@
clean:
	rm -f 214.ShortestPalindrome 1392.LongestHappyPrefix 2430.MaximumDeletionsonaString 2565.SubsequenceWiththeMinimumScore
