ex:218.TheSkylineProblem 2515.ShortestDistancetoTargetStringinaCircularArray 2520.CounttheDigitsThatDivideaNumber 2535.DifferenceBetweenElementSumandDigitSumofanArray 2552.CountIncreasingQuadruplets 2553.SeparatetheDigitsinanArray 2554.MaximumNumberofIntegerstoChooseFromaRangeI 2566.MaximumDifferencebyRemappingaDigit
218.TheSkylineProblem:218.TheSkylineProblem.cc lib.a
	g++ -Wall -g $^ -o $@
2515.ShortestDistancetoTargetStringinaCircularArray:2515.ShortestDistancetoTargetStringinaCircularArray.cc
	g++ -Wall -g $^ -o $@
2520.CounttheDigitsThatDivideaNumber:2520.CounttheDigitsThatDivideaNumber.cc
	g++ -Wall -g $^ -o $@
2535.DifferenceBetweenElementSumandDigitSumofanArray:2535.DifferenceBetweenElementSumandDigitSumofanArray.cc
	g++ -Wall -g $^ -o $@
2552.CountIncreasingQuadruplets:2552.CountIncreasingQuadruplets.cc
	g++ -Wall -g $^ -o $@
2553.SeparatetheDigitsinanArray:2553.SeparatetheDigitsinanArray.cc lib.a
	g++ -Wall -g $^ -o $@
2554.MaximumNumberofIntegerstoChooseFromaRangeI:2554.MaximumNumberofIntegerstoChooseFromaRangeI.cc
	g++ -Wall -g -std=c++11 $^ -o $@
2566.MaximumDifferencebyRemappingaDigit:2566.MaximumDifferencebyRemappingaDigit.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 218.TheSkylineProblem 2515.ShortestDistancetoTargetStringinaCircularArray 2520.CounttheDigitsThatDivideaNumber 2535.DifferenceBetweenElementSumandDigitSumofanArray 2552.CountIncreasingQuadruplets 2553.SeparatetheDigitsinanArray 2554.MaximumNumberofIntegerstoChooseFromaRangeI 2566.MaximumDifferencebyRemappingaDigit
