ex:840.MagicSquaresInGrid 2515.ShortestDistancetoTargetStringinaCircularArray 2520.CounttheDigitsThatDivideaNumber 2535.DifferenceBetweenElementSumandDigitSumofanArray 2554.MaximumNumberofIntegerstoChooseFromaRangeI 2566.MaximumDifferencebyRemappingaDigit 2578.SplitWithMinimumSum 2586.CounttheNumberofVowelStringsinRange 2600.KItemsWiththeMaximumSum
218.TheSkylineProblem:218.TheSkylineProblem.cc lib.a
	g++ -Wall -g $^ -o $@
840.MagicSquaresInGrid:840.MagicSquaresInGrid.cc
	g++ -Wall -g $^ -o $@
1846.MaximumElementAfterDecreasingandRearranging:1846.MaximumElementAfterDecreasingandRearranging.cc
	g++ -Wall -g $^ -o $@
2515.ShortestDistancetoTargetStringinaCircularArray:2515.ShortestDistancetoTargetStringinaCircularArray.cc
	g++ -Wall -g $^ -o $@
2520.CounttheDigitsThatDivideaNumber:2520.CounttheDigitsThatDivideaNumber.cc
	g++ -Wall -g $^ -o $@
2535.DifferenceBetweenElementSumandDigitSumofanArray:2535.DifferenceBetweenElementSumandDigitSumofanArray.cc
	g++ -Wall -g $^ -o $@
2552.CountIncreasingQuadruplets:2552.CountIncreasingQuadruplets.cc
	g++ -Wall -g $^ -o $@
2553.SeparatetheDigitsinanArray:2553.SeparatetheDigitsinanArray.cc lib.a
	g++ -Wall -g $^ -o $@
2554.MaximumNumberofIntegerstoChooseFromaRangeI:2554.MaximumNumberofIntegerstoChooseFromaRangeI.cc
	g++ -Wall -g -std=c++11 $^ -o $@
2566.MaximumDifferencebyRemappingaDigit:2566.MaximumDifferencebyRemappingaDigit.cc
	g++ -Wall -g $^ -o $@
2578.SplitWithMinimumSum:2578.SplitWithMinimumSum.cc
	g++ -Wall -g $^ -o $@
2586.CounttheNumberofVowelStringsinRange:2586.CounttheNumberofVowelStringsinRange.cc
	g++ -Wall -g $^ -o $@
2600.KItemsWiththeMaximumSum:2600.KItemsWiththeMaximumSum.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 218.TheSkylineProblem 840.MagicSquaresInGrid 2515.ShortestDistancetoTargetStringinaCircularArray 2520.CounttheDigitsThatDivideaNumber 2535.DifferenceBetweenElementSumandDigitSumofanArray 2552.CountIncreasingQuadruplets 2553.SeparatetheDigitsinanArray 2554.MaximumNumberofIntegerstoChooseFromaRangeI 2566.MaximumDifferencebyRemappingaDigit 2578.SplitWithMinimumSum 2586.CounttheNumberofVowelStringsinRange 2600.KItemsWiththeMaximumSum
