ex:2525.CategorizeBoxAccordingtoCriteria 2562.FindtheArrayConcatenationValue
2525.CategorizeBoxAccordingtoCriteria:2525.CategorizeBoxAccordingtoCriteria.cc
	g++ -Wall -g $^ -o $@
2562.FindtheArrayConcatenationValue:2562.FindtheArrayConcatenationValue.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 2525.CategorizeBoxAccordingtoCriteria 2562.FindtheArrayConcatenationValue
