ex:1599.MaximumProfitofOperatingaCentennialWheel 1958.CheckifMoveisLegal 2162.MinimumCosttoSetCookingTime 2525.CategorizeBoxAccordingtoCriteria 2562.FindtheArrayConcatenationValue 2596.CheckKnightTourConfiguration
lib.a:head.o
	ar -crv $@ $<
head.o:head.cc
1599.MaximumProfitofOperatingaCentennialWheel:1599.MaximumProfitofOperatingaCentennialWheel.cc
	g++ -Wall -g $^ -o $@
1958.CheckifMoveisLegal:1958.CheckifMoveisLegal.cc
	g++ -Wall -g $^ -o $@
2162.MinimumCosttoSetCookingTime:2162.MinimumCosttoSetCookingTime.cc
	g++ -Wall -g $^ -o $@
2525.CategorizeBoxAccordingtoCriteria:2525.CategorizeBoxAccordingtoCriteria.cc
	g++ -Wall -g $^ -o $@
2562.FindtheArrayConcatenationValue:2562.FindtheArrayConcatenationValue.cc
	g++ -Wall -g $^ -o $@
2596.CheckKnightTourConfiguration:2596.CheckKnightTourConfiguration.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 1599.MaximumProfitofOperatingaCentennialWheel 1958.CheckifMoveisLegal 2162.MinimumCosttoSetCookingTime 2525.CategorizeBoxAccordingtoCriteria 2562.FindtheArrayConcatenationValue 2596.CheckKnightTourConfiguration
