ex:911.OnlineElection 1381.DesignaStackWithIncrementOperation 1845.SeatReservationManager 1865.FindingPairsWithaCertainSum 2013.DetectSquares 2526.FindConsecutiveIntegersfromaDataStream
855.ExamRoom:855.ExamRoom.cc
	g++ -Wall -g $^ -o $@
911.OnlineElection:911.OnlineElection.cc
	g++ -Wall -g $^ -o $@
1381.DesignaStackWithIncrementOperation:1381.DesignaStackWithIncrementOperation.cc
	g++ -Wall -g $^ -o $@
1845.SeatReservationManager:1845.SeatReservationManager.cc
	g++ -Wall -g $^ -o $@
1865.FindingPairsWithaCertainSum:1865.FindingPairsWithaCertainSum.cc
	g++ -Wall -g $^ -o $@
2013.DetectSquares:2013.DetectSquares.cc
	g++ -Wall -g $^ -o $@
2526.FindConsecutiveIntegersfromaDataStream:2526.FindConsecutiveIntegersfromaDataStream.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 855.ExamRoom 911.OnlineElection 1381.DesignaStackWithIncrementOperation 1845.SeatReservationManager 1865.FindingPairsWithaCertainSum 2013.DetectSquares 2526.FindConsecutiveIntegersfromaDataStream
