ex:855.ExamRoom 2526.FindConsecutiveIntegersfromaDataStream
855.ExamRoom:855.ExamRoom.cc
	g++ -Wall -g $^ -o $@
2526.FindConsecutiveIntegersfromaDataStream:2526.FindConsecutiveIntegersfromaDataStream.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 855.ExamRoom 2526.FindConsecutiveIntegersfromaDataStream
