ex:84.LargestRectangleinHistogram
84.LargestRectangleinHistogram:84.LargestRectangleinHistogram.h 84.LargestRectangleinHistogram.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f lib.a *.o 84.LargestRectangleinHistogram
