ex:2418.SortthePeople 2570.MergeTwo2DArraysbySummingValues
2418.SortthePeople:2418.SortthePeople.cc lib.a
	g++ -Wall -g $^ -o $@
2570.MergeTwo2DArraysbySummingValues:2570.MergeTwo2DArraysbySummingValues.cc lib.a
	g++ -Wall -g $^ -o $@
clean:
	rm -f 2418.SortthePeople 2570.MergeTwo2DArraysbySummingValues
