ex:lib.a 798.SmallestRotationwithHighestScore 1072.FlipColumnsForMaximumNumberofEqualRows 1109.CorporateFlightBookings 1523.CountOddNumbersinanIntervalRange 1590.MakeSumDivisiblebyP 1854.MaximumPopulationYear 2017.GridGame 2055.PlatesBetweenCandles  2132.StampingtheGrid 2245.MaximumTrailingZerosinaCorneredPath  2256.MinimumAverageDifference 2270.NumberofWaystoSplitArray 2271.MaximumWhiteTilesCoveredbyaCarpet 2321.MaximumScoreOfSplicedArray 2348.NumberofZero-FilledSubarrays 2406.DivideIntervalsIntoMinimumNumberofGroups 2488.CountSubarraysWithMedianK
lib.a:head.o
	ar -crv $@ $<
head.o:head.cc
798.SmallestRotationwithHighestScore:798.SmallestRotationwithHighestScore.cc
	g++ -Wall -g $^ -o $@
1072.FlipColumnsForMaximumNumberofEqualRows:1072.FlipColumnsForMaximumNumberofEqualRows.cc
	g++ -Wall -g -std=c++11  $^ -o $@
1109.CorporateFlightBookings:1109.CorporateFlightBookings.cc lib.a
	g++ -Wall -g -std=c++11  $^ -o $@
1523.CountOddNumbersinanIntervalRange:1523.CountOddNumbersinanIntervalRange.cc
	g++ -Wall -g -std=c++11  $^ -o $@
1590.MakeSumDivisiblebyP:1590.MakeSumDivisiblebyP.cc
	g++ -Wall -g -std=c++11  $^ -o $@
1854.MaximumPopulationYear:1854.MaximumPopulationYear.cc
	g++ -Wall -g -std=c++11  $^ -o $@
2017.GridGame:2017.GridGame.cc
	g++ -Wall -g -std=c++11  $^ -o $@
2055.PlatesBetweenCandles:2055.PlatesBetweenCandles.cc lib.a
	g++ -Wall -g -std=c++11  $^ -o $@
2132.StampingtheGrid:2132.StampingtheGrid.cc
	g++ -Wall -g $^ -o $@
2245.MaximumTrailingZerosinaCorneredPath:2245.MaximumTrailingZerosinaCorneredPath.cc
	g++ -Wall -g $^ -o $@
2256.MinimumAverageDifference:2256.MinimumAverageDifference.cc
	g++ -Wall -g $^ -o $@
2270.NumberofWaystoSplitArray:2270.NumberofWaystoSplitArray.cc
	g++ -Wall -g $^ -o $@
2271.MaximumWhiteTilesCoveredbyaCarpet:2271.MaximumWhiteTilesCoveredbyaCarpet.cc
	g++ -Wall -g $^ -o $@
2321.MaximumScoreOfSplicedArray:2321.MaximumScoreOfSplicedArray.cc
	g++ -Wall -g $^ -o $@
2348.NumberofZero-FilledSubarrays:2348.NumberofZero-FilledSubarrays.cc
	g++ -Wall -g $^ -o $@
2406.DivideIntervalsIntoMinimumNumberofGroups:2406.DivideIntervalsIntoMinimumNumberofGroups.cc
	g++ -Wall -g $^ -o $@
2488.CountSubarraysWithMedianK:2488.CountSubarraysWithMedianK.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 798.SmallestRotationwithHighestScore 1072.FlipColumnsForMaximumNumberofEqualRows 1109.CorporateFlightBookings 1523.CountOddNumbersinanIntervalRange 1590.MakeSumDivisiblebyP 1854.MaximumPopulationYear 2017.GridGame 2055.PlatesBetweenCandles 2132.StampingtheGrid 2245.MaximumTrailingZerosinaCorneredPath  2256.MinimumAverageDifference 2270.NumberofWaystoSplitArray 2271.MaximumWhiteTilesCoveredbyaCarpet 2321.MaximumScoreOfSplicedArray 2348.NumberofZero-FilledSubarrays 2406.DivideIntervalsIntoMinimumNumberofGroups 2488.CountSubarraysWithMedianK
