ex:2527.FindXor-BeautyofArray 2564.SubstringXORQueries
233.NumberofDigitOne:233.NumberofDigitOne.cc
	g++ -Wall -g $^ -o $@
2527.FindXor-BeautyofArray:2527.FindXor-BeautyofArray.cc
	g++ -Wall -g $^ -o $@
2564.SubstringXORQueries:2564.SubstringXORQueries.cc lib.a
	g++ -Wall -g $^ -o $@
clean:
	rm -f 233.NumberofDigitOne 2527.FindXor-BeautyofArray 2564.SubstringXORQueries
