ex:2017.GridGame 2202.MaximizetheTopmostElementAfterKMoves
2017.GridGame:2017.GridGame.cc
	g++ -Wall -g $^ -o  $@
2202.MaximizetheTopmostElementAfterKMoves:2202.MaximizetheTopmostElementAfterKMoves.cc
	g++ -Wall -g $^ -o  $@
clean:
	rm -f 2017.GridGame 2202.MaximizetheTopmostElementAfterKMoves
