ex:363.MaxSumofRectangleNoLargerThanK 2035.PartitionArrayIntoTwoArraystoMinimizeSumDifference 2040.KthSmallestProductofTwoSortedArrays 2071.MaximumNumberofTasksYouCanAssign 2516.TakeKofEachCharacterFromLeftandRight 2517.MaximumTastinessofCandyBasket 2528.MaximizetheMinimumPoweredCity 2529.MaximumCountofPositiveIntegerandNegativeInteger 2576.FindtheMaximumNumberofMarkedIndices 2577.MinimumTimetoVisitaCellInaGrid 2594.MinimumTimetoRepairCars 2602.MinimumOperationstoMakeAllArrayElementsEqual 2616.MinimizetheMaximumDifferenceofPairs
lib.a:head.o
	ar -crv $@ $<
head.o:head.cc
363.MaxSumofRectangleNoLargerThanK:363.MaxSumofRectangleNoLargerThanK.cc
	g++ -Wall -g $^ -o $@
975.OddEvenJump:975.OddEvenJump.cc
	g++ -Wall -g $^ -o $@
2035.PartitionArrayIntoTwoArraystoMinimizeSumDifference:2035.PartitionArrayIntoTwoArraystoMinimizeSumDifference.cc
	g++ -Wall -g $^ -o $@
2040.KthSmallestProductofTwoSortedArrays:2040.KthSmallestProductofTwoSortedArrays.cc
	g++ -Wall -g $^ -o $@
2071.MaximumNumberofTasksYouCanAssign:2071.MaximumNumberofTasksYouCanAssign.cc
	g++ -Wall -g $^ -o $@
2516.TakeKofEachCharacterFromLeftandRight:2516.TakeKofEachCharacterFromLeftandRight.cc
	g++ -Wall -g $^ -o $@
2517.MaximumTastinessofCandyBasket:2517.MaximumTastinessofCandyBasket.cc
	g++ -Wall -g $^ -o $@
2528.MaximizetheMinimumPoweredCity:2528.MaximizetheMinimumPoweredCity.cc
	g++ -Wall -g $^ -o $@
2529.MaximumCountofPositiveIntegerandNegativeInteger:2529.MaximumCountofPositiveIntegerandNegativeInteger.cc
	g++ -Wall -g $^ -o $@
2560.HouseRobberIV:2560.HouseRobberIV.cc
	g++ -Wall -g $^ -o $@
2576.FindtheMaximumNumberofMarkedIndices:2576.FindtheMaximumNumberofMarkedIndices.cc
	g++ -Wall -g $^ -o $@
2577.MinimumTimetoVisitaCellInaGrid:2577.MinimumTimetoVisitaCellInaGrid.cc
	g++ -Wall -g $^ -o $@
2594.MinimumTimetoRepairCars:2594.MinimumTimetoRepairCars.cc
	g++ -Wall -g $^ -o $@
2602.MinimumOperationstoMakeAllArrayElementsEqual:2602.MinimumOperationstoMakeAllArrayElementsEqual.cc lib.a
	g++ -Wall -g $^ -o $@
2616.MinimizetheMaximumDifferenceofPairs:2616.MinimizetheMaximumDifferenceofPairs.cc
	g++ -Wall -g $^ -o $@
clean:
	rm -f 363.MaxSumofRectangleNoLargerThanK 975.OddEvenJump 2035.PartitionArrayIntoTwoArraystoMinimizeSumDifference 2040.KthSmallestProductofTwoSortedArrays 2071.MaximumNumberofTasksYouCanAssign 2516.TakeKofEachCharacterFromLeftandRight 2517.MaximumTastinessofCandyBasket 2528.MaximizetheMinimumPoweredCity 2529.MaximumCountofPositiveIntegerandNegativeInteger 2560.HouseRobberIV 2576.FindtheMaximumNumberofMarkedIndices 2577.MinimumTimetoVisitaCellInaGrid 2594.MinimumTimetoRepairCars 2602.MinimumOperationstoMakeAllArrayElementsEqual 2616.MinimizetheMaximumDifferenceofPairs
